### ISSUE TITLE
flat_correct doesn't normalize flat field for uncertainty array

### ISSUE THREAD

**Issue by mheida** [astropy/ccdproc#345] opened 2016-04-20 19:44 UTC
When using flat_correct on an image with an uncertainty array the flat field is normalized before the data is divided through it, but not for the uncertainty array.

**Comment by crawfordsm** [comment] 2016-04-20 19:47
Thanks for pointing this out.  If you are interested in putting in a PR to fix this please let us know.  Otherwise we will fix it as soon as we can as this is a bug.

**Comment by MSeifert04** [comment] 2016-04-26 09:14
I think this is already fixed in astropy: https://github.com/astropy/astropy/issues/4152

**Comment by mwcraig** [comment] 2016-05-17 19:19
I'll add logic in ccdproc to handle it if `astropy<1.2` in case there are users counoting on the astropy LTS (1.0.x).

**Comment by mwcraig** [comment] 2016-06-22 19:51
@mheida -- sorry for the delay. What version of astropy and ccdproc are you using? It looks like this may already be fixed  (or at least when I try to reproduce it with the latest (unreleased) ccdproc it seem to be working).

**Comment by mheida** [comment] 2016-06-22 19:58
Both my astropy and ccdproc are version 1.0.1

**Comment by mwcraig** [comment] 2016-06-22 20:33
I'm having trouble reproducing the issue -- would it be a hassle to provide a code snippet that reproduces it? What I've been trying is below, in case I'm not correctly understanding when the issue arises:

```python
import numpy as np
from ccdproc import flat_correct, CCDData
dat = CCDData(np.ones([100, 100]), unit='adu', uncertainty=np.ones([100, 100]))
# Note flat is set to 10, error is set to one.
flat = CCDData(10 * np.ones([100, 100]), unit='adu', uncertainty=1 * np.ones([100, 100]))
res = flat_correct(dat, flat)
res.uncertainty.array  # Returns 1.00498756, which is sqrt(1^2+0.1^2)
```

**Comment by MSeifert04** [comment] 2016-06-22 20:43
@mwcraig This formula is only half true, you need multiply it with ``dat/flat`` .

With astropy-master:

```
>>> dat = NDDataRef(np.ones([100, 100]), unit='adu', uncertainty=StdDevUncertainty(np.ones([100, 100])))
# Note flat is set to 10, error is set to one.
>>> flat = NDDataRef(10 * np.ones([100, 100]), unit='adu', uncertainty=StdDevUncertainty(np.ones([100, 100])))
>>> res = dat.divide(flat)
>>> res.uncertainty
StdDevUncertainty([[ 0.10049876,  0.10049876,  0.10049876, ...,
                     0.10049876,  0.10049876,  0.10049876],
                   [ 0.10049876,  0.10049876,  0.10049876, ...,
                     0.10049876,  0.10049876,  0.10049876],
                   [ 0.10049876,  0.10049876,  0.10049876, ...,
                     0.10049876,  0.10049876,  0.10049876],
                   ..., 
                   [ 0.10049876,  0.10049876,  0.10049876, ...,
                     0.10049876,  0.10049876,  0.10049876],
                   [ 0.10049876,  0.10049876,  0.10049876, ...,
                     0.10049876,  0.10049876,  0.10049876],
                   [ 0.10049876,  0.10049876,  0.10049876, ...,
                     0.10049876,  0.10049876,  0.10049876]])
```

**Comment by mwcraig** [comment] 2016-06-22 21:04
@MSeifert04 -- thanks, but I *think* that is a slightly different case?   `flat_correct` divides by `flat.mean()` at https://github.com/astropy/ccdproc/blob/master/ccdproc/core.py#L711-L712 (well, technically, it multiplies `dat/flat` by `flat.mean`).

So the case on master should be, I think `>>> res = dat.divide(flat/flat.mean())` (or maybe `flat.data.mean()`).

**Comment by mheida** [comment] 2016-06-22 21:06
I get the same result as you, but I noticed that I was using a flat frame without uncertainties and apparently then the errors are propagated differently.
>>> dat = CCDData(np.ones([100, 100]), unit='adu', uncertainty=np.ones([100, 100]))
>>> flat2 = CCDData(10 * np.ones([100, 100]), unit='adu')
>>> res2 = ccdproc.flat_correct(dat, flat2)
>>> res2.uncertainty.array
array([[ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       ..., 
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.]])

Is this supposed to happen? Anyway, I should probably include uncertainties in the flatfield.

**Comment by MSeifert04** [comment] 2016-06-22 21:13
@mwcraig You are right, I missed that. :disappointed: Looking at @mheida example code it looks a lot like https://github.com/astropy/astropy/issues/4152.

**Comment by mwcraig** [comment] 2016-06-22 21:15
@mheida -- ah, that makes sense! Well, the *result* makes no sense, but now I understand why it is happening.

**Comment by mwcraig** [comment] 2016-06-22 21:18
@MSeifert04 -- yep, I think that is it, thanks for tracking down the PR. I'm thinking I'll just repeat some of the logic from those fixes in `_ccddata_arithmetic` when the astropy version is less than 1.2.

**Comment by mwcraig** [comment] 2016-06-22 21:25
> Anyway, I should probably include uncertainties in the flatfield.

Maybe...in practice I don't do that, FWIW.

**Closed** 2016-07-01 13:29 UTC
Labels: affects-release, bug, ccdproc
