### ISSUE TITLE
Performing minmax clipping on Combiner is returning a NoneType

### ISSUE THREAD

**Issue by JPVentura135** [astropy/ccdproc#606] opened 2017-12-29 07:04 UTC
Hi all,

My goal is to A.) `minmax_clipping()` mask a Combiner.

Im having trouble getting a stacked image because after I mask the Combiner and set to a variable, a NoneType is returned. My code is below:

```
...
flatlist_OH = []
for filename in allfiles.files_filtered(OBSTYPE='SKY FLAT',FILTERS='OH'):
    ccd = fits.getdata(allfiles.location + filename)
    ccd = cp.CCDData(ccd, unit= u.adu)
    ccd = cp.subtract_overscan(ccd,overscan_axis=1,overscan = ccd[:,3099:3125])
    ccd = cp.trim_image(ccd,fits_section='[27:3095,3:3078]')
    ccd = cp.subtract_bias(ccd,cp.CCDData(fits.getdata(path + 'mbias_avg.fits'),unit = u.adu))
    flatlist_OH.append(ccd)

combinerOH = cp.Combiner(flatlist_OH.copy())
maskedCombinerOH = combinerOH.minmax_clipping(min_clip=11300.0)
```

All checks out until the last line. Upon verifying:

```
In [15]: maskedCombinerOH
In [16]: 

In [16]: type(maskedCombinerOH)
Out[16]: NoneType
```

for reference:
astropy version 2.0.2
ccdproc version 1.3.0

**Comment by MSeifert04** [comment] 2017-12-29 11:04
Thank you for opening the issue.

`minmax_clipping` works in-place so the instance you call it on (`combinerOH`) is actually changed. For such in-place methods the Python convention is to return `None` to avoid confusion.

This is by design, so I'm closing this issue.

**Closed by MSeifert04** 2017-12-29 11:04 UTC
