### ISSUE TITLE
Writing out mask, flags, uncertainty information

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#52] opened 2014-05-06 18:17 UTC
For now any flag, mask and/or unit for ccddata is discarded when writing. If you want all or some of that information preserved you must create the FITS files manually.   

It would be good to be able to write out that information as well.

**Comment by mwcraig** [comment] 2015-03-16 18:46
Closing this as a duplicate of #196

**Closed by mwcraig** 2015-03-16 18:46 UTC
Labels: CCDData, enhancement
