### ISSUE TITLE
cosmicray_median bug?

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/ccdproc#433] opened 2016-12-06 22:41 UTC
Hi,

I'm trying to run cosmicray_median on some HST data, and i'm getting an astropy WCS error.  The odd thing about it is that in the traceback there's no listing of what line of cosmicray_median it's coming from, and I'm a bit stumped, as it seems like cosmicray_median shouldn't need to do anything with the WCS in the first place, since no transformations are happening.

I tried to look at some of the WCS bugs in this repo from the past, and didn't see anything offhand, but I'm also not running with the ccdproc dev version, just the latest version on conda, but certainly let me know if you want me to fork the dev and run a local test with it:

ccdproc                   1.1.0                    py27_0    astropy
astropy                   1.2.1               np111py27_0 
numpy                     1.11.1                   py27_0  

Now that I'm printing these, I should mention that I haven't trolled the astropy package for this error, but an initial google search didn't show up much.

```
test_data = '/eng/ssb/iraf_transition/test_data/iczgs3y5q_flt.fits'
image_data = fits_ccddata_reader(test_data, hdu=1, unit=units.electron/units.s), hdu_uncertainty=2)
newdata, mask = cosmicray_median(image_data, error_image=error_data, thresh=5, mbox=11, rbox=11, gbox=3)
```

traceback is:

```
ValueError                                Traceback (most recent call last)
<ipython-input-16-9687261d18f7> in <module>()
      8 
      9 # Now we run cosmicray_median
---> 10 newdata, mask = cosmicray_median(image_data, error_image=error_data, thresh=5, mbox=11, rbox=11, gbox=3)

/Users/ogaz/miniconda2/envs/irafdev/lib/python2.7/site-packages/astropy/nddata/mixins/ndslicing.pyc in __getitem__(self, item)
     59 
     60         # Let the other methods handle slicing.
---> 61         kwargs = self._slice(item)
     62         return self.__class__(**kwargs)
     63 

/Users/ogaz/miniconda2/envs/irafdev/lib/python2.7/site-packages/astropy/nddata/mixins/ndslicing.pyc in _slice(self, item)
     89         kwargs['uncertainty'] = self._slice_uncertainty(item)
     90         kwargs['mask'] = self._slice_mask(item)
---> 91         kwargs['wcs'] = self._slice_wcs(item)
     92         # Attributes which are copied and not intended to be sliced
     93         kwargs['unit'] = self.unit

/Users/ogaz/miniconda2/envs/irafdev/lib/python2.7/site-packages/astropy/nddata/mixins/ndslicing.pyc in _slice_wcs(self, item)
    119             return None
    120         try:
--> 121             return self.wcs[item]
    122         except TypeError:
    123             log.info("wcs cannot be sliced.")

/Users/ogaz/miniconda2/envs/irafdev/lib/python2.7/site-packages/astropy/wcs/wcs.pyc in __getitem__(self, item)
   2954         # We COULD allow wcs[1] to link to wcs.sub([2])
   2955         # (wcs[i] -> wcs.sub([i+1])
-> 2956         return self.slice(item)
   2957 
   2958     def __iter__(self):

/Users/ogaz/miniconda2/envs/irafdev/lib/python2.7/site-packages/astropy/wcs/wcs.pyc in slice(self, view, numpy_order)
   2914 
   2915         if not all([isinstance(x, slice) for x in view]):
-> 2916             raise ValueError("Cannot downsample a WCS with indexing.  Use "
   2917                              "wcs.sub or wcs.dropaxis if you want to remove "
   2918                              "axes.")

ValueError: Cannot downsample a WCS with indexing.  Use wcs.sub or wcs.dropaxis if you want to remove axes.
```

On a complete side note, it looks like cosmicray_median is making a recursive call when you hand it a full CCDData object, this seems like an odd design choice to me, is there an advantage to doing it that way, is it common?

Thanks!

**Comment by SaraOgaz** [comment] 2016-12-06 22:43
Also, you guys may be happy to know, we're trying to include ``ccdproc`` in our notebook tutorials when we can for STAK (https://github.com/spacetelescope/stak).

**Comment by MSeifert04** [comment] 2016-12-06 23:09
@SaraOgaz Thanks for the report and I suspect that the documentation is inaccurate.

The problem is that if you input a `CCDData` then you get a `CCDData` back and the problem is that you expect 2 returned arguments. 

Could you try if this works:

`new_ccd = cosmicray_median(image_data, error_image=error_data, thresh=5, mbox=11, rbox=11, gbox=3)`

**Comment by MSeifert04** [comment] 2016-12-06 23:10
> Also, you guys may be happy to know, we're trying to include ccdproc in our notebook tutorials when we can for STAK

Very nice indeed. I certainly will have a look at these 🎉 👍

**Comment by SaraOgaz** [comment] 2016-12-07 15:31
@MSeifert04  ahh, my bad, didn't read the doc examples carefully enough! Just getting normal looking errors nows.

**Comment by mwcraig** [comment] 2016-12-13 03:09
@SaraOgaz -- closing because it looks like this is resolved, but if not please reopen it.

**Closed by mwcraig** 2016-12-13 03:09 UTC
Labels: bug, ccdproc, docs
