### ISSUE TITLE
Building ccdproc on OSX with py37 fails due to astroscrappy build error

### ISSUE THREAD

**Issue by bsipocz** [astropy/ccdproc#646] opened 2018-11-16 01:32 UTC
I'm trying to build ccdproc on OSX on Python 3.7 when astroscrappy is not installed. So this is upstream from here, yet affects ccdproc.
Everything works as expected with Python3.6

```
✔ ~/munka/devel/ccdproc [hacking|⚑ 1] $ pt -R
Freezing version number to ./ccdproc/version.py
running test
Searching for reproject
Reading https://pypi.org/simple/reproject/
Downloading https://files.pythonhosted.org/packages/99/db/205157c0c3d2942a6ae421cf5cfa7a5d870b511ba9e538ceb0117bb0ca01/reproject-0.4.tar.gz#sha256=dbbb18a8b211292c7ce61121b8538fc279540337be1c05cabc7570c5aca6d734
Best match: reproject 0.4
Processing reproject-0.4.tar.gz
Writing /var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/easy_install-xsrjwq16/reproject-0.4/setup.cfg
Running reproject-0.4/setup.py -q bdist_egg --dist-dir /var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/easy_install-xsrjwq16/reproject-0.4/egg-dist-tmp-b907eo1h
In file included from reproject/spherical_intersect/_overlap.c:525:
In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
/usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using
      deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
1 warning generated.
reproject/spherical_intersect/overlapArea.c:929:7: warning: 'finite' is deprecated: first deprecated in macOS 10.9
      [-Wdeprecated-declarations]
  if (mNaN(area) || area < 0.)
      ^
reproject/spherical_intersect/mNaN.h:10:32: note: expanded from macro 'mNaN'
  #define mNaN(x) isnan(x) || !finite(x)
                               ^
/usr/include/math.h:757:12: note: 'finite' has been explicitly marked deprecated here
extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
           ^
1 warning generated.
creating /Users/bsipocz/munka/devel/ccdproc/.eggs/reproject-0.4-py3.7-macosx-10.13-x86_64.egg
Extracting reproject-0.4-py3.7-macosx-10.13-x86_64.egg to /Users/bsipocz/munka/devel/ccdproc/.eggs

Installed /Users/bsipocz/munka/devel/ccdproc/.eggs/reproject-0.4-py3.7-macosx-10.13-x86_64.egg
Searching for astroscrappy
Reading https://pypi.org/simple/astroscrappy/
Downloading https://files.pythonhosted.org/packages/80/12/899e09a3dee9055fb1428c22a42ca65e24242c4491a30de982af38cea792/astroscrappy-1.0.5.tar.gz#sha256=29f6ab8809fb404c369f0a63c74ec72a11fbe872650dd08906caf6ab801c2920
Best match: astroscrappy 1.0.5
Processing astroscrappy-1.0.5.tar.gz
Writing /var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/easy_install-yaya6b3u/astroscrappy-1.0.5/setup.cfg
Running astroscrappy-1.0.5/setup.py -q bdist_egg --dist-dir /var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/easy_install-yaya6b3u/astroscrappy-1.0.5/egg-dist-tmp-bdszu30f
OpenMP was not found. astroscrappy will be compiled without OpenMP. (Use the "-v" option of setup.py for more details.)
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
astroscrappy/astroscrappy.c:27186:21: error: no member named 'exc_type' in 'struct _ts'
    *type = tstate->exc_type;
            ~~~~~~  ^
astroscrappy/astroscrappy.c:27187:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    *value = tstate->exc_value;
                     ^~~~~~~~~
                     curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 
      'curexc_value' declared here
    PyObject *curexc_value;
              ^
astroscrappy/astroscrappy.c:27188:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean
      'curexc_traceback'?
    *tb = tstate->exc_traceback;
                  ^~~~~~~~~~~~~
                  curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 
      'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
astroscrappy/astroscrappy.c:27195:24: error: no member named 'exc_type' in 'struct _ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
astroscrappy/astroscrappy.c:27196:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 
      'curexc_value' declared here
    PyObject *curexc_value;
              ^
astroscrappy/astroscrappy.c:27197:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean
      'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 
      'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
astroscrappy/astroscrappy.c:27198:13: error: no member named 'exc_type' in 'struct _ts'
    tstate->exc_type = type;
    ~~~~~~  ^
astroscrappy/astroscrappy.c:27199:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tstate->exc_value = value;
            ^~~~~~~~~
            curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 
      'curexc_value' declared here
    PyObject *curexc_value;
              ^
astroscrappy/astroscrappy.c:27200:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean
      'curexc_traceback'?
    tstate->exc_traceback = tb;
            ^~~~~~~~~~~~~
            curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 
      'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
astroscrappy/astroscrappy.c:27255:24: error: no member named 'exc_type' in 'struct _ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
astroscrappy/astroscrappy.c:27256:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 
      'curexc_value' declared here
    PyObject *curexc_value;
              ^
astroscrappy/astroscrappy.c:27257:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean
      'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 
      'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
astroscrappy/astroscrappy.c:27258:13: error: no member named 'exc_type' in 'struct _ts'
    tstate->exc_type = local_type;
    ~~~~~~  ^
astroscrappy/astroscrappy.c:27259:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tstate->exc_value = local_value;
            ^~~~~~~~~
            curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 
      'curexc_value' declared here
    PyObject *curexc_value;
              ^
astroscrappy/astroscrappy.c:27260:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean
      'curexc_traceback'?
    tstate->exc_traceback = local_tb;
            ^~~~~~~~~~~~~
            curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 
      'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
astroscrappy/astroscrappy.c:27282:24: error: no member named 'exc_type' in 'struct _ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
astroscrappy/astroscrappy.c:27283:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 
      'curexc_value' declared here
    PyObject *curexc_value;
              ^
astroscrappy/astroscrappy.c:27284:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean
      'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 
      'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
astroscrappy/astroscrappy.c:27285:13: error: no member named 'exc_type' in 'struct _ts'
    tstate->exc_type = *type;
    ~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: Setup script exited with error: command 'clang' failed with exit status 1
```

**Comment by MSeifert04** [comment] 2018-11-17 22:36
Yeah it affects `ccdproc` but we cannot really do anything about that. If I remember correctly we didn't want to have optional dependencies, however if it's impossible to actually install `ccdproc` on certain systems because of a dependency we might need to change that.

Did you already file an issue at astroscrappy? This looks like a genuine python 3.7 incompatibility that needs to be addressed.

**Comment by bsipocz** [comment] 2018-11-18 04:01
No worries @MSeifert04, I was just testing the astropy RC :)

I haven't followed up directly with astroscrappy. It also hasn't yet been build on conda-forge, but at least a PR has been opened for it.

**Comment by mwcraig** [comment] 2018-11-19 17:54
So we can maybe fix this just with a cython upgrade? https://github.com/cython/cython/issues/1955 

Still going to track down the travis logs and/or try building locally to make sure I can reproduce. The error is coming from the generated `.c` file, though, not the `.pyx` source.

**Comment by mwcraig** [comment] 2018-11-19 18:44
@bsipocz -- I am able to compile astroscrappy master locally on OSX 10.13.6/Python 3.7 using cython 0.29. 

However, I'm unable to build `1.05` I think because of a helpers issue (the helpers version in astroscrappy 1.05 is 1.2), so it looks like building astroscrappy for conda-forge, etc, will require a new astroscrappy release.

**Comment by bsipocz** [comment] 2018-11-19 19:17
I see. Also, I suppose for that new astroscrappy release it would be great to have the new helpers, but for that we need to figure out a few more stuff, so no point in rushing a release out now while we can have a slightly better one in a few weeks time...

**Comment by MSeifert04** [comment] 2018-11-19 19:29
I guess we don't have to rush Python 3.7 compatibility. :)

**Comment by bsipocz** [comment] 2018-11-19 19:38
Hmm, 2 more weeks doesn't make a difference...

**Comment by mwcraig** [comment] 2018-11-19 20:17
Ah, I wasn't clear that a new astroscrappy release is coming.  I could see maybe doing a patch for Python 3.7/astroscrappy 1.0.5 on conda-forge just to minimize the headaches on a short-term basis, but it won't be at the top of my list to get done, either...

**Comment by bsipocz** [comment] 2018-11-19 20:20
I'm not sure it's coming, but I suppose if we were pushing for it, Curtis would do a release.

**Comment by mwcraig** [comment] 2019-03-08 17:34
This is now fixed, closing.

**Closed by mwcraig** 2019-03-08 17:34 UTC
Labels: reviewed-for-2.0
